[build-system]
requires = [
    "setuptools>=38", # Used to build and package the Python project
    "pybind11>=2.2", # Builds python - cpp interface for direct calls to galsim cpp layer
    "wheel"
]
build-backend = "setuptools.build_meta"