{% set name = "batsim" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  skip: true  # [py<310 or py>=313]

requirements:
  build:
    - {{ compiler('c')}}
    - {{ compiler('cxx')}}
  host:
    - python {{ python }}
    - pip
    - setuptools
    - wheel
    - pybind11 >=3,<4
    - eigen
    - numpy >=1.26,<2.0
    - galsim
    - fitsio
    - llvm-openmp # [osx]
  run:
    - python >=3.10,<3.13
    - numpy >=1.26,<2.0
    - galsim
    - fitsio
    - matplotlib >=3.8,<3.9
    - astropy
    - llvm-openmp # [osx]

test:
  imports:
    - batsim
    - batsim._gsinterface

about:
  license: MIT
  summary: "BATSim package with GalSim C++ sampling and optional CuPy GPU support"
