# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Git checkout currect repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        show-channel-urls: true

    - name: configure conda and install code
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes
        conda install mamba
        mamba install flake8 pytest numpy galsim black fitsio \
          matplotlib astropy pybind11

        python -m pip install --upgrade pip
        pip install -U setuptools

        pip install . --user


    - name: Lint with black
      shell: bash -l {0}
      run: |
        black src/batsim

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
